name: Releases

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make release
        run: make
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run:
          gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${tag#v}" --generate-notes build/TicTacToe
