name: Releases

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    name: Release pushed tag
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            artifact: "ubuntu.7z",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generators: "Ninja"
          }
          - {
            name: "MacOS Latest",
            os: macos-latest,
            artifact: "mac.7z",
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            archiver: "7za a",
            generators: "Ninja"
          }
    steps:
      - uses: actions/checkout@v4
      - name: Make release
        run: make
      - name: Rename executable
        run: mv build/TicTacToe build/TicTacToe-${{ github.runner_os }}
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          RUNNER_OS: ${{ github.runner_os }}
        run:
          echo "Configuring for $(RUNNER_OS) [$(uname)].";
          if [[ "$(gh release view $tag 2>&1)" == "release not found" ]]; then
            echo "Release not found. Creating release.";
            gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${tag#v}" --generate-notes build/TicTacToe-"$(uname)";
          else
            echo "Release found. Appending files to release.";
            gh release upload "$tag" build/TicTacToe-"$(uname)";
          fi;
